name: Experimental Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    branches: [ master ]
    tags: ['**']


jobs:

  # Test on latest PyPy 2.7 and 3.x versions with Linux and latest SDL2
  test-linux:

    name: Linux (${{ matrix.python-version }}, SDL ${{ matrix.sdl2 }})
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        python-version: ['pypy-2.7', 'pypy-3.7']
        sdl2: ['2.0.14']

    env:
      SDL_VIDEODRIVER: dummy
      SDL_AUDIODRIVER: dummy
      SDL_RENDER_DRIVER: software
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and latest SDL2 binaries
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy pytest pillow
          python -m pip install pysdl2-dll
      
      - name: Install and test PySDL2
        run: |
          python -m pip install .
          python -B -m pytest -vvl -rxXP


  # Test on previous Python release with macOS using latest Homebrew SDL2
  test-macos:

    name: macOS (Python ${{ python-version }}, Homebrew SDL2)
    runs-on: macos-latest
    continue-on-error: true

    python-version: '3.8'

    env:
      SDL_VIDEODRIVER: dummy
      SDL_RENDER_DRIVER: software
    
    steps:
      - uses: actions/checkout@v2

      - name: Install latest SDL2 via Homebrew
        run: |
          brew install sdl2 sdl2_mixer sdl2_ttf sdl2_image sdl2_gfx

      - name: Set up Python ${{ python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy pytest pillow

      - name: Install and test PySDL2
        run: |
          python -m pip install .
          python -B -m pytest -vvl -rxXP
