name: Test PySDL2 on Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    branches: [ master ]
    tags: ['**']

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        experimental: [false]
        include:
          - python-version: 'pypy-2.7'
            experimental: true
          - python-version: 'pypy-3.7'
            experimental: true

    env:
      SDL_VIDEODRIVER: dummy
      SDL_AUDIODRIVER: dummy
      SDL_RENDER_DRIVER: software
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and latest SDL2 binaries
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy pytest pillow
          python -m pip install pysdl2-dll
      
      - name: Install and test PySDL2
        run: |
          python -m pip install .
          python -B -m pytest -vvl -rxXP
